### ISSUE TITLE
Wayfinder and weblink issue

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#571]
Myn subnav is gone when the folder page is a weblink.
Switching it back to normal page its visible again.

evo 1.1
```
<nav id="nav" class="nav">
	[[Wayfinder? 
	&startId=`0` 
	&firstClass=`first` 
	&level=`2` 
	&sortOrder=`ASC` 
	&sortBy=`menuindex`
	&rowTpl=`navRowTpl`
	&parentRowTpl=`navParentRowTpl`
	]]  
</nav>
```

navParentRowTpl
`<li class="has-submenu [+wf.classnames+]"><a href="[+wf.link+]">[+wf.linktext+]</a><div class="down"></div>[+wf.wrapper+]</li>`

its not a css problem. the subnav disappears

**Comment by MrSwed** [comment]
See [changes ](https://github.com/modxcms/evolution/commits/master/assets/snippets/wayfinder/snippet.wayfinder.php)
May be
[That](https://github.com/modxcms/evolution/commit/7be7aca815c044787e120d21ebbb55e101cc4328#diff-d26053fdab6614573c5811453488b9d7R64):
```
 // for local references - use original ID of document (useful for set class="active" in references)
```
Default true. try to set referenceUseOriginalID false

**Comment by fourroses666** [comment]
As quick fix I used FirstChildRedirect (in this case YAMSFirstChildRedirect).
When changing it back to weblink the subnav is visible again, so it probably must have been a pritty hard cache issue  _I really hate cache_
----------

I'm having an other issue with using weblinks but will add a new one.

**Comment by fourroses666** [comment]
Hmm, having the issue on an other site now. (not a YAMS site).
Again had to use FirstChildRedirect to fix it.

Btw, is there a reason its default?

**Comment by MrSwed** [comment]
I corrected the previous comment.
As for the "default", probably in most cases the use of links needed to precisely such behavior, and therefore set by default. maybe not worth it.
what result with
&useReferenced=\`0\` ?

**Comment by fourroses666** [comment]
That doesn't fix it, getting an "unlimited redirect".
You don't have this issue?

**Comment by MrSwed** [comment]
"incorrect/unlimited redirect" - is something else..
need more details

**Comment by fourroses666** [comment]
I will make a copy and give you login so you can see and test for yourself.

**Comment by MrSwed** [comment]
ok

**Comment by fourroses666** [comment]
@MrSwed I have a copy and made a login user for you.
Do you have slqack or an emailadres?

**Comment by MrSwed** [comment]
replied to email. got?
and .. you can see addresses in the git history

**Comment by fourroses666** [comment]
Hey, bit hectic on my side, very very busy.
But I have got no email. Did you receive the login ?

**Comment by MrSwed** [comment]
i send to .. [at] graffx.nl..
ok,  [write](https://github.com/modxcms/evolution/blob/2770263464c1391be0c1577b3aa9b4c7136142a2/assets/plugins/managermanager/widgets/mm_minimizablesections/mm_minimizablesections.php#L15) when be free

**Comment by fourroses666** [comment]
I have send you an email yesterday!
Did a resend to your emailaddress.

**Comment by MrSwed** [comment]
&useReferenced=`` - thats is

**Comment by fourroses666** [comment]
Yes, it works when using:
`&useReferenced="0"`

Just tested, updated snippets/wayfinder/
Doesn't work in Development version!

**Comment by Deesen** [comment]
Can you send me login-details too so I can check?

**Comment by fourroses666** [comment]
done!

**Comment by fourroses666** [comment]
Only remark I have is that its a bit weird to add this `&useReferenced="0"` to my Wayfinder calls while it used to work. 

I know this probably doesn't happen on too many sites but I can't think of a situation when you need `&useReferenced="1"`. For me `&useReferenced="1"` is the normal/default behaviour.
